name: CronJob
on:
  pull_request:

jobs:
  list_unreleased:
    runs-on: ubuntu-latest
    outputs:
      vs_tags: ${{ steps.generate.outputs.vs_tags }}
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: "3.7"
      - uses: abatilo/actions-poetry@v2
        with:
          poetry-version: "1.1.15"
      - name: Generate Unreleased VSCode Tags
        id: generate
        run: |
          poetry install
          TAGS=$(poetry run python hack/tools.py list-unreleased-tags)
          echo vs_tags=${TAGS} >> $GITHUB_OUTPUT

  release_tag:
    runs-on: ubuntu-latest
    needs:
      - list_unreleased
    strategy:
      fail-fast: false
      matrix:
        vs_tag: ${{ fromJSON(needs.list_unreleased.outputs.vs_tags) }}
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: "3.7"
      - uses: abatilo/actions-poetry@v2
        with:
          poetry-version: "1.1.15"
      - name: New Unreleased VSCode Tag
        id: generate
        continue-on-error: true
        run: |
          poetry install
          poetry run python hack/tools.py update-server-bin ${{ matrix.vs_tag }}
          cat vscode_server_bin/vscode-commit-id
          version=$(echo ${{ matrix.vs_tag }} | tr ':' ' ' | awk '{print $1}')
          git config user.name 'ZhengYu, Xu'
          git config user.email 'zen-xu@outlook.com'
          git remote set-url origin https://x-access-token:${{ secrets.GIT_TOKEN }}@github.com/$GITHUB_REPOSITORY
          git add vscode_server_bin/
          git commit -m "Bump version $version"
          git tag $version
          git push --tags
